name: Elixir CI

on:
    - push
    - pull_request

permissions:
    contents: read

jobs:
    build:
        name: Build and test
        runs-on: ubuntu-latest

        strategy:
            matrix:
                elixir_version: ['1.14', '1.15']
                otp_version: ['25.0']

        steps:
            - uses: actions/checkout@v3
            - name: Set up Elixir
              uses: erlef/setup-beam@61e01a43a562a89bfc54c7f9a378ff67b03e4a21
              with:
                  elixir-version: ${{matrix.elixir_version}}
                  otp-version: ${{matrix.otp_version}}
            - name: Restore dependencies cache
              uses: actions/cache@v3
              with:
                  path: deps
                  key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
                  restore-keys: ${{ runner.os }}-mix-
            - name: Install dependencies
              run: make install
            - name: Run tests
              run: make test
            - name: Check formatting
              run: make check-format
